;****************************************************;
; Alias
;****************************************************;
(alias int INTEGER)
(alias float FLOAT)
(alias bool BOOL)
(alias string STRING)
(alias list LIST)
(alias expr EXPRESSION)
(alias new def)

;****************************************************;
; Optimize attribute 
;****************************************************;
(add-attribute !=                atom)
(add-attribute %                 atom)
(add-attribute &                 atom)
(add-attribute *                 atom)
(add-attribute +                 atom)
(add-attribute -                 atom)
(add-attribute /                 atom)
(add-attribute <                 atom)
(add-attribute <=                atom)
(add-attribute =                 atom)
(add-attribute >                 atom)
(add-attribute >=                atom)
(add-attribute ^                 atom)
(add-attribute |                 atom)
(add-attribute ~                 atom)
(add-attribute and               atom)
(add-attribute not               atom)
(add-attribute or                atom)
(add-attribute power             atom)
(add-attribute str-char-at       atom)
(add-attribute str-end-with      atom)
(add-attribute str-equal         atom)
(add-attribute str-equal-nocase  atom)
(add-attribute str-format        atom)
(add-attribute str-index-of      atom)
(add-attribute str-last-index-of atom)
(add-attribute str-length        atom)
(add-attribute str-match         atom)
(add-attribute str-replace       atom)
(add-attribute str-split         atom)
(add-attribute str-split-line    atom)
(add-attribute str-start-with    atom)
(add-attribute str-substr        atom)
(add-attribute str-trim          atom)
(add-attribute str-trim-head     atom)
(add-attribute str-trim-tail     atom)
(add-attribute str-upper         atom)
(add-attribute strcat            atom)
(add-attribute to-int            atom)

(add-attribute !=                    stable)
(add-attribute %                     stable)
(add-attribute &                     stable)
(add-attribute *                     stable)
(add-attribute +                     stable)
(add-attribute -                     stable)
(add-attribute /                     stable)
(add-attribute ::                    stable)
(add-attribute <                     stable)
(add-attribute <=                    stable)
(add-attribute =                     stable)
(add-attribute >                     stable)
(add-attribute >=                    stable)
(add-attribute ^                     stable)
(add-attribute access                stable)
(add-attribute add-array-to-list     stable)
(add-attribute add-attribute         stable)
(add-attribute add-list-to-array     stable)
(add-attribute add-list-to-list      stable)
(add-attribute alias                 stable)
(add-attribute and                   stable)
(add-attribute attribute-of          stable)
(add-attribute blob-length           stable)
(add-attribute break                 stable)
(add-attribute can-cast              stable)
(add-attribute case                  stable)
(add-attribute class-of              stable)
(add-attribute cmp_def               stable)
(add-attribute compute               stable)
(add-attribute continue              stable)
(add-attribute defclass              stable)
(add-attribute defconst              stable)
(add-attribute deftemplate           stable)
(add-attribute defun                 stable)
(add-attribute defvar                stable)
(add-attribute do                    stable)
(add-attribute do-when-obj-deleted   stable)
(add-attribute do-when-var-changed   stable)
(add-attribute equal_def             stable)
(add-attribute foreach               stable)
(add-attribute get-of-array          stable)
(add-attribute get-of-list           stable)
(add-attribute has-member            stable)
(add-attribute if                    stable)
(add-attribute is-const              stable)
(add-attribute join                  stable)
(add-attribute lambda                stable)
(add-attribute let                   stable)
(add-attribute loop                  stable)
(add-attribute list-of               stable)
(add-attribute make-array            stable)
(add-attribute make-blob             stable)
(add-attribute make-list             stable)
(add-attribute make-string           stable)
(add-attribute name-of               stable)
(add-attribute new                   stable)
(add-attribute not                   stable)
(add-attribute or                    stable)
(add-attribute power                 stable)
(add-attribute property-of           stable)
(add-attribute ref                   stable)
(add-attribute remove-all-list       stable)
(add-attribute return                stable)
(add-attribute reverse               stable)
(add-attribute seta                  stable)
(add-attribute setq                  stable)
(add-attribute size-of-array         stable)
(add-attribute size-of-list          stable)
(add-attribute sort-list             stable)
(add-attribute str-char-at           stable)
(add-attribute str-end-with          stable)
(add-attribute str-equal             stable)
(add-attribute str-equal-nocase      stable)
(add-attribute str-format            stable)
(add-attribute str-index-of          stable)
(add-attribute str-last-index-of     stable)
(add-attribute str-length            stable)
(add-attribute str-match             stable)
(add-attribute str-replace           stable)
(add-attribute str-split             stable)
(add-attribute str-start-with        stable)
(add-attribute str-substr            stable)
(add-attribute str-trim              stable)
(add-attribute str-trim-head         stable)
(add-attribute str-trim-tail         stable)
(add-attribute str-upper             stable)
(add-attribute strcat                stable)
(add-attribute subject-of            stable)
(add-attribute to-atom               stable)
(add-attribute to-blob               stable)
(add-attribute to-expr               stable)
(add-attribute to-int                stable)
(add-attribute to-named-list         stable)
(add-attribute to-nonamed-list       stable)
(add-attribute to-string             stable)
(add-attribute type-of               stable)
(add-attribute union                 stable)
(add-attribute uniq                  stable)
(add-attribute value-of              stable)
(add-attribute value-type-of         stable)
(add-attribute when                  stable)
(add-attribute write-blob            stable)
(add-attribute |                     stable)
(add-attribute ~                     stable)

(add-attribute load              thread-unsafe)
(add-attribute print             thread-unsafe)
(add-attribute print-frame-tree  thread-unsafe)
(add-attribute print-global-info thread-unsafe)
(add-attribute print-subject     thread-unsafe) 
(add-attribute print-frame-tree  thread-unsafe) 
(add-attribute print-impl        thread-unsafe) 
(add-attribute out-to-file       thread-unsafe) 
(add-attribute open-txt-file     thread-unsafe)
(add-attribute save-txt-file     thread-unsafe) 

(add-attribute and  return-type  bool)
(add-attribute or   return-type  bool)
(add-attribute not  return-type  bool)

(add-attribute +                 return-type  1)
(add-attribute -                 return-type  1)
(add-attribute *                 return-type  1)
(add-attribute /                 return-type  1)
(add-attribute str-char-at       return-type  int)
(add-attribute str-end-with      return-type  bool)
(add-attribute str-equal         return-type  bool)
(add-attribute str-equal-nocase  return-type  bool)
(add-attribute str-format        return-type  string)
(add-attribute str-index-of      return-type  int)
(add-attribute str-last-index-of return-type  int)
(add-attribute str-length        return-type  int)
(add-attribute str-match         return-type  bool)
(add-attribute str-replace       return-type  string)
(add-attribute str-split         return-type  list)
(add-attribute str-split-line    return-type  list)
(add-attribute str-start-with    return-type  bool)
(add-attribute str-substr        return-type  string)
(add-attribute str-trim          return-type  string)
(add-attribute str-trim-head     return-type  string)
(add-attribute str-trim-tail     return-type  string)
(add-attribute str-upper         return-type  string)

;****************************************************;
; Basic tools
;****************************************************;
(defun length-of ((?l string)) (return (str-length ?l)))
(defun length-of ((?l blob)) (return (blob-length ?l)))

(defun equal (?l ?2) (return (equal_def ?l ?2)))
(defun equal ((?l string) (?2 string)) (return (str-equal ?l ?2)))

(defun cmp (?l ?2) (return (cmp_def ?l ?2)))

(defun println ()                                    (print "\n"))
(defun println (?a1)                                 (print ?a1 "\n"))
(defun println (?a1 ?a2)                             (print ?a1 ?a2 "\n"))
(defun println (?a1 ?a2 ?a3)                         (print ?a1 ?a2 ?a3 "\n"))
(defun println (?a1 ?a2 ?a3 ?a4)                     (print ?a1 ?a2 ?a3 ?a4 "\n"))
(defun println (?a1 ?a2 ?a3 ?a4 ?a5)                 (print ?a1 ?a2 ?a3 ?a4 ?a5 "\n"))
(defun println (?a1 ?a2 ?a3 ?a4 ?a5 ?a6)             (print ?a1 ?a2 ?a3 ?a4 ?a5 ?a6 "\n"))
(defun println (?a1 ?a2 ?a3 ?a4 ?a5 ?a6 ?a7)         (print ?a1 ?a2 ?a3 ?a4 ?a5 ?a6 ?a7 "\n"))
(defun println (?a1 ?a2 ?a3 ?a4 ?a5 ?a6 ?a7 ?a8)     (print ?a1 ?a2 ?a3 ?a4 ?a5 ?a6 ?a7 ?a8 "\n"))
(defun println (?a1 ?a2 ?a3 ?a4 ?a5 ?a6 ?a7 ?a8 ?a9) (print ?a1 ?a2 ?a3 ?a4 ?a5 ?a6 ?a7 ?a8 ?a9 "\n"))

;****************************************************;
; Enviroment vars
;****************************************************;
(defvar ?path (make-list))
;(defvar ?load-system (make-list))
(defvar ?load-class (make-list))
(defvar ?load-jar (make-list))
(defvar ?load-script (make-list))

;****************************************************;
; List tools
;****************************************************;
(defun size-of  ((?l list)) (return (size-of-list ?l)))
(defun is-empty ((?l list)) (return (equal (size-of-list ?l) 0)))
(defun to-list  ((?l list)) (return ?l))
(defun to-array ((?l list)) (return (add-list-to-array (make-array) ?l)))

(defun add ((?l list) ?e0) (return (add-list-to-list ?l '(?e0))))
(defun add ((?l list) ?e0 ?e1) (return (add-list-to-list ?l '(?e0 ?e1))))
(defun add ((?l list) ?e0 ?e1 ?e2) (return (add-list-to-list ?l '(?e0 ?e1 ?e2))))
(defun add-all ((?l1 list) (?l2 list)) (return (add-list-to-list ?l1 ?l2)))

(defun get ((?l list) (?i int)) (return (get-of-list ?l ?i)))

(defun index-of (?obj (?list list))
    (defvar ?pos (- (size-of ?list) 1))    
    (loop 
        (if (< ?pos 0) 
            (break))
        (defvar ?obj2 (get ?list ?pos))
        (if (equal ?obj ?obj2)
            (break))
        (-- ?pos)
    )    
    (return ?pos)
)

(defun remove ((?l list) ?e0) (return (remove-all-list ?l '(?e0))))
(defun remove-all ((?l1 list) (?l2 list)) (return (remove-all-list ?l1 ?l2)))

;****************************************************;
; Array tools
;****************************************************;
(defun size-of  ((?arr array)) (return (size-of-array ?arr)))
(defun size-of  ((?arr array) (?dim int)) (return (size-of-array ?arr ?dim)))
(defun is-empty ((?arr array)) (return (equal (size-of-array ?arr) 0)))
(defun to-list  ((?arr array)) (return (add-array-to-list '() ?arr)))

(defun add ((?a array) ?e0) (return (add-list-to-array ?a '(?e0))))
(defun add ((?a array) ?e0 ?e1) (return (add-list-to-array ?a '(?e0 ?e1))))
(defun add ((?a array) ?e0 ?e1 ?e2) (return (add-list-to-array ?a '(?e0 ?e1 ?e2))))

(defun get ((?arr array) (?i1 int)) (return (get-of-array ?arr ?i1)))
(defun get ((?arr array) (?i1 int) (?i2 int)) (return (get-of-array ?arr ?i1 ?i2)))

;****************************************************;
; Iterator tools
;****************************************************;
(defun to-list  ((?it iterator)) 
    (defvar ?arr (make-array))
    (loop 
        (if (not (has-next ?it))
            (break)
        )
        (add ?arr (next ?it))
    )
    (return (to-list ?arr))
)

;****************************************************;
; Namespace tools
;****************************************************;
(deftemplate use ((namespace atom) (?ns namespace))
    (add_search_frame parent (frame-of $(value-of ?ns)))
)

(deftemplate use ((namespace atom) (?ns frame))
    (add_search_frame parent ?ns)
)

(deftemplate use (namespace ?ns)
    (throw bad-type (strcat "namespace not found: " (to-string ?ns)))
)

